name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "21.x"

      - name: Install dependencies
        run: cd frontend && npm install

  BUild_and_deploy:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: ${{ secrets.AWS_REGISTRY_URL }}

      - name: Build and push Docker image
        run: |
          cd frontend
          docker build -t ${{ secrets.AWS_REGISTRY_URL }}/codegenitor:${{ github.run_number }} .
          docker push ${{ secrets.AWS_REGISTRY_URL }}/codegenitor:${{ github.run_number }}
