name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      # frontend setup
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "21.x"

      # frontend install dependencies
      - name: Install dependencies
        run: cd frontend && npm install

      # frontend run tests

  BUild_and_deploy:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build and deploy to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          dockerfile: frontend/Dockerfile
          repository-name: frontend
          create-repo: false
          tags: latest, ${{ github.run_number }}
          daemon_off: false
